version: '3'

services:
  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - internal
    volumes:
      - type: volume
        source: backend-app
        target: /app
    ports:
      - '3000:3000'
    entrypoint: sh /tmp/entry.sh
    env_file:
      - env/.env

  redis:
    container_name: redis
    build:
      context: redis
      dockerfile: Dockerfile
    networks:
      - internal
    entrypoint: sh /tmp/entry.sh
    volumes:
      - redis-log:/data

networks:
  internal:
    name: internal
    driver: bridge

volumes:
  backend-app:
    name: backend-app
    driver: local
    driver_opts:
      device: ./app
      type: none
      o: bind

  redis-log:
    name: redis-log
    driver: local
    driver_opts:
      device: ./redis/redis-log
      type: none
      o: bind
