version: "3"

services:
  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - internal
    volumes:
      - type: volume
        source: backend-app
        target: /app
      - "./env:/env"
    ports:
      - "80:80"
    entrypoint: sh -c 'pnpm i && pnpm start:dev'

networks:
  internal:
    name: internal
    driver: bridge

volumes:
  backend-app:
    name: backend-app
    driver: local
    driver_opts:
      device: ./app
      type: none
      o: bind
