version: "3"

services:
  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - internal
    volumes:
      - type: volume
        source: backend-app
        target: /app
    ports:
      - "80:80"
    entrypoint: sh /tmp/entry.sh
    env_file:
      - env/.env.prod
    environment:
      - PROD=true

networks:
  internal:
    name: internal
    driver: bridge

volumes:
  backend-app:
    name: backend-app
    driver: local
    driver_opts:
      device: ./app
      type: none
      o: bind
