version: '3'

services:
  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - type: volume
        source: backend-app
        target: /app
    ports:
      - '3000:3000'
    entrypoint: sh /tmp/entry.sh
    env_file:
      - env/.env

volumes:
  backend-app:
    name: backend-app
    driver: local
    driver_opts:
      device: ./app
      type: none
      o: bind
