name: Deploy Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Deploy Dev
    runs-on: ubuntu-22.04

    steps:
      - name: Deploy to Dev EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_DEV_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "move to repository"
            cd $HOME/42Stat-Backend
            echo "pull"
            git pull origin dev
            echo "env update"
            git submodule update --remote
            echo "run docker"
            docker-compose -f docker-compose.dev.yml down -v
            docker-compose -f docker-compose.dev.yml up -d
